#
# Software Name : helm
{{- if and .Values.cdr.enabled .Values.cdr.uploader.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chf.cdr.secretName" . }}
type: Opaque
stringData:
  id_ed25519: | {{- required "Set cdr.uploader.sftp.auth.privatekey (via --set-file)" .Values.cdr.uploader.sftp.auth.privatekey | nindent 4 }}
  known_hosts: |-
{{- if .Values.cdr.uploader.sftp.knownHosts }}
{{ .Values.cdr.uploader.sftp.knownHosts | nindent 4 }}
{{- end }}
{{- end }}
