{{- if and .Values.sftp.enabled .Values.sftp.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chf.fullname" . }}-sftp-ssh-key
type: Opaque
stringData:
  authorized_keys: |
{{ .Values.sftp.authorizedKeys | indent 4 }}
{{- end }}
