#
# Software Name : helm
#
nameOverride: ""
fullnameOverride: ""

global:
  projectName: chf
  nrf:
    service:
      name: service-enterprise1-slice1-nfmanagement.ns-enterprise1.svc.cluster.local #change namespace
      type: ClusterIP
      port: "8080"
      mutalTls: false
  webui: 
    service:
      name: webui-nbiling
      type: ClusterIP
      port: "2122"
  cgf:
    service:
      name: webui-ncgf
      type: ClusterIP
      port: "2121"
  sbi:
    scheme: http
    mutalTls: false

# This section can be used to override the default values in the MongoDB chart (remember MongoDB is a subchart of the chart since control plane NFs rely on it.
mongodb:
  service:
    name: mongodb
    type: ClusterIP
    port: 27017

chf:
  name: chf
  replicaCount: 1
  image:
    name: myregistrydomain.com:5000/chf-nsf
    tag: 21
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  configmap:
    name: chf-configmap
  volume:
    mount: /chf/config/
    tlsmount: /chf/config/TLS
    certmount: /chf/nrf-cert
  podAnnotations: {}
    # additional annotations
  imagePullSecrets:
    - name: my-private-registry-secret
  podSecurityContext: 
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: 
    allowPrivilegeEscalation: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration: 
    serviceNameList: |-
      - nchf-convergedcharging # Nchf_AMPolicyControl service
    
    # Metrics configuration
    metrics:
      enable: false # (Optional, default false)
      scheme: http # (Required) the protocol for metrics (http or https, default https)
      port: 9091 # (Optional, default 9091) port used to bind the service
      namespace: ns-chf

    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false

    plmnSupportList: # the PLMNs (Public land mobile network) list supported by this AMF
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: "608" # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: "01" # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: "19CDE1" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd:  # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: "608" # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: "01" # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: "010203" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: "112233" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
initcontainers:
  busybox:
    image: busybox
    tag: "1.32.0"

sftp:
  enabled: true
  # Image built from your Dockerfile (contains dropbear + entrypoint)
  exportSubPath : export
  image:
    repository: myregistrydomain.com:5000/chf-sftp
    tag: v1
    pullPolicy: Always
  imagePullSecrets:
    - my-private-registry-secret
  replicas: 1
  port: 2222
  # Attach Multus NAD (string). Examples:
  # "nad-sftp" or '[{"name":"nad-sftp","interface":"net1"}]'
  networksAnnotation: '[{"name": "nad-sftp", "interface": "net1", "ips": ["192.168.1.27/24"]}]'
  # Use the SAME CephFS PVC that CHF uses
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  # RAFT client public key(s)
  authorizedKeys: |
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

cdr:
  enabled: true
  basePath: /data/cdr
  pvc:
    create: true
    name: ""                   # auto-name via helper
    storageClassName: nfs-client   # CHANGE to your RWX class
    size: 20Gi
    accessModes:
      - ReadWriteMany
  archiveJobs:
    compress:
      enabled: true
      schedule: "0 * * * *"     # every hour
      timeZone: ""              # optional; requires K8s >= 1.27 (e.g., "UTC" or "Africa/Casablanca")
      image:
        repository: myregistrydomain.com:5000/alpine
        tag: "3.20"
        pullPolicy: Always
      imagePullSecrets:
        - my-private-registry-secret
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
    retention:
      enabled: true
      schedule: "0 3 * * 0"     # Sundays at 03:00
      timeZone: ""              # optional; requires K8s >= 1.27
      keepDays: 7               # delete .csv.gz older than 7 days
      image:
        repository: myregistrydomain.com:5000/alpine
        tag: "3.20"
        pullPolicy: Always
      imagePullSecrets:
        - my-private-registry-secret
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true